#
all: zk_cluster zk_tree zk_write zk_watch

zk_cluster: zk_cluster.go
	go build zk_cluster.go

zk_tree: zk_tree.go
	go build zk_tree.go

zk_write: zk_write.go
	go build zk_write.go

zk_watch: zk_watch.go
	go build zk_watch.go
